apiVersion: v1
kind: Secret
metadata:
    name: flask-secret
    namespace: flask-namespace
type: Opaque
data:
    PGDB_PASSWORD: ENC[AES256_GCM,data:oySevYLJqhed1dtC,iv:qU5mnDV3FOXpCXoRY2sDia6WJb6Qn9TWMBGONmlJ42k=,tag:Pz1p/Z6nOuM8LVh162HGRA==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/ica-1-436122/locations/northamerica-northeast1/keyRings/my-keyring/cryptoKeys/my-key
          created_at: "2024-11-19T19:11:05Z"
          enc: CiQAYANxOdjJJaIeqpGZqdg5deEIdYtoZUPR6XdTXkBU+k5/cVMSSQD/QvdJwOneBX/5JMqoff3ZWdtmGTKkuDExPzE5Yps4CficHNxZIv7Qy8eLfPYgBfntx1Tl49d8+DaoluAfJ2h2rd9+6yh6j4U=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-19T19:11:06Z"
    mac: ENC[AES256_GCM,data:taco7aFnjSzONnud8U7mR79JDCKoyMihy1QVfG/QqHLlJq5kgao7dq0nPSB+zDDQhqOqDx1RFUREfbP7lelUYbfVlJ4gD115+aPEZnWlJHZ4y7AtZUex5QEjGytUZu8dxp+I2eoRGEm6mVqCpmzM1k0jg5eJpWVSNZUjjyoCBEY=,iv:m+xRn2cNvSip38RoBJeYyXsZ+xAjMzI52DUSsO74CA0=,tag:p7OcI+/AxIklzpbS1j0V1w==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
