apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: post-namespace
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP